name: Test & publish to PyPI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read      # nötig für actions/checkout
  id-token: write     # << erforderlich für Trusted Publishing

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"   # nutzt deine dev‑Extras
      - name: Run tests
        run: pytest

  build-and-publish:
    needs: test            # ← läuft nur, wenn Job 'test' erfolgreich war
    runs-on: ubuntu-latest
    environment: pypi      # muss zu PyPI‑Konfiguration passen
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build dist
        run: |
          python -m pip install --upgrade build
          python -m build           # erzeugt dist/*.whl und *.tar.gz

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true       # überschreibt keine identische Version
